#tag::setDatabaseName[]

spring:
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:h2:tcp://localhost/~/${BASE_NAME}
    username: sa
    password: asd123

  application:
    name: step3_DATA_JDBC



logging:
  level:
    sql: debug

taco:
  orders:
    pageSize: 2
#end::setDatabaseName[]