#tag::setDatabaseName[]

spring:

  datasource:
    url: jdbc:postgresql://localhost:5436/gele_main
    username: gele_usr
    password: gele_usr
    hikari:
      schema: taco_step4

  application:
    name: step3_DATA_JDBC
#  sql:
#    init:
#      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    generate-ddl: true
#logging:
#  level:
#    sql: debug

taco:
  orders:
    pageSize: 5
#end::setDatabaseName[]