#tag::setDatabaseName[]

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5436/gele_main?currentSchema=taco_step4
    username: gele_usr
    password: gele_usr

  application:
    name: step3_DATA_JDBC



logging:
  level:
    sql: debug

taco:
  orders:
    pageSize: 2
#end::setDatabaseName[]