#tag::setDatabaseName[]

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/taco_step4
    username: sa
    password: asd123

  application:
    name: step3_DATA_JDBC


logging:
  level:
    sql: debug

#end::setDatabaseName[]