
#tag::setDatabaseName[]


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    password: 1
    username: sa
  application:
    name: step3_DATA_JDBC
logging:
  level:
    sql: debug

#end::setDatabaseName[]